from pydantic import BaseModel, Field

class DCFAssumptionsSchema(BaseModel):
    """
    Schema for the DCF assumptions and narrative justification generated by the LLM.
    """
    fcf_growth_1_to_5: float = Field(..., description="Projected free cash flow growth rate for years 1 to 5 (e.g., 0.15 for 15%)")
    fcf_growth_6_to_10: float = Field(..., description="Projected free cash flow growth rate for years 6 to 10 (e.g., 0.10 for 10%)")
    wacc: float = Field(..., description="Weighted Average Cost of Capital (discount rate) (e.g., 0.085 for 8.5%)")
    terminal_growth_rate: float = Field(..., description="Perpetual growth rate after year 10 (e.g., 0.025 for 2.5%)")
    justification: str = Field(..., description="Analytical narrative justifying these specific rates based on the company's moat and macro environment.")

class DCFValuationResponseSchema(BaseModel):
    """
    Schema encompassing the three required DCF scenarios.
    """
    bear: DCFAssumptionsSchema
    fair: DCFAssumptionsSchema
    bull: DCFAssumptionsSchema
